workers_dev = true
name = "hono-react-router"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]
main = "./worker.ts"
assets = { directory = "./build/client/" }

[vars]
TEST = "abc"
